name: b11-workflow

on: workflow_dispatch

jobs:

  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: print messege
        run: |

             sleep 10
           
             echo "This is 1st job ..."


  second-job:
    runs-on: ubuntu-22.04
    needs: first-job
    steps:
      - name: print message for 2nd job
        run: | 
            
            sleep 5 
            echo "This is 2nd job ..."