name: Action-workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create a file and view it
        run: |
          echo "test" > report.txt
          cat report.txt
