name: b13-workflow

on: push

jobs:
  run-additional: 
    runs-on: ubuntu-latest
    steps:
      - name: create a file and view it
        run: |
            echo "test" > report.txt
            cat report.txt
